"""
Handlers layer - Event handlers and presenters.

Generated by: implementation-agent
Source: docs/design/structure/STRUCT-APP-001-project-layout.md
Generated: 2025-11-12T23:10:00Z
Requirements: FR-GUI-002
"""
