"""
Edit menu action handlers.

Generated by: implementation-agent
Source: docs/design/structure/CLASS-GUI-002-menu-system.md
Generated: 2025-11-12T23:10:00Z
Requirements: FR-GUI-002
"""

from typing import Optional
from PySide6.QtWidgets import QWidget, QMessageBox


class EditActionHandler:
    """
    Handler for Edit menu actions.

    Handles:
        - Edit → Undo: Show "Undo clicked" message
        - Edit → Redo: Show "Redo clicked" message

    Related: FR-GUI-002 (AC-GUI-002-07, AC-GUI-002-08)
    Generated: 2025-11-12T23:10:00Z
    """

    def __init__(self, parent: QWidget):
        """
        Initialize handler with parent window reference.

        Args:
            parent: Parent widget (MainWindow)

        Related: FR-GUI-002
        """
        self.parent = parent

    def on_undo(self) -> None:
        """
        Handle Edit → Undo action.

        Displays a message box with "Undo clicked" text.

        Related: FR-GUI-002 (AC-GUI-002-07)
        Generated: 2025-11-12T23:10:00Z
        """
        try:
            QMessageBox.information(
                self.parent,
                "SimplePySideApp",
                "Undo clicked"
            )
        except Exception as e:
            self._handle_error("Undo action", e)

    def on_redo(self) -> None:
        """
        Handle Edit → Redo action.

        Displays a message box with "Redo clicked" text.

        Related: FR-GUI-002 (AC-GUI-002-08)
        Generated: 2025-11-12T23:10:00Z
        """
        try:
            QMessageBox.information(
                self.parent,
                "SimplePySideApp",
                "Redo clicked"
            )
        except Exception as e:
            self._handle_error("Redo action", e)

    def _handle_error(self, context: str, error: Exception) -> None:
        """
        Handle action errors.

        Logs error to console and displays error dialog to user.

        Args:
            context: Description of the action that failed
            error: Exception that was raised

        Related: FR-GUI-002 (BR-GUI-004)
        """
        print(f"ERROR [{context}]: {error}")
        try:
            QMessageBox.critical(
                self.parent,
                "Error",
                f"An error occurred: {context}"
            )
        except Exception:
            # If error dialog fails, just log
            pass
