"""
File menu action handlers.

Generated by: implementation-agent
Source: docs/design/structure/CLASS-GUI-002-menu-system.md
Generated: 2025-11-12T23:10:00Z
Requirements: FR-GUI-002, BR-GUI-001
"""

from typing import Optional
from PySide6.QtWidgets import QWidget, QMessageBox, QApplication


class FileActionHandler:
    """
    Handler for File menu actions.

    Handles:
        - File → New: Show "New clicked" message
        - File → Open: Show "Open clicked" message
        - File → Save: Show "Save clicked" message
        - File → Exit: Close application cleanly

    Related: FR-GUI-002 (AC-GUI-002-01 through AC-GUI-002-05)
    Generated: 2025-11-12T23:10:00Z
    """

    def __init__(self, parent: QWidget):
        """
        Initialize handler with parent window reference.

        Args:
            parent: Parent widget (MainWindow)

        Related: FR-GUI-002
        """
        self.parent = parent

    def on_new(self) -> None:
        """
        Handle File → New action.

        Displays a message box with "New clicked" text.

        Related: FR-GUI-002 (AC-GUI-002-01, AC-GUI-002-02)
        Generated: 2025-11-12T23:10:00Z
        """
        try:
            QMessageBox.information(
                self.parent,
                "SimplePySideApp",
                "New clicked"
            )
        except Exception as e:
            self._handle_error("New action", e)

    def on_open(self) -> None:
        """
        Handle File → Open action.

        Displays a message box with "Open clicked" text.

        Related: FR-GUI-002 (AC-GUI-002-03)
        Generated: 2025-11-12T23:10:00Z
        """
        try:
            QMessageBox.information(
                self.parent,
                "SimplePySideApp",
                "Open clicked"
            )
        except Exception as e:
            self._handle_error("Open action", e)

    def on_save(self) -> None:
        """
        Handle File → Save action.

        Displays a message box with "Save clicked" text.

        Related: FR-GUI-002 (AC-GUI-002-04)
        Generated: 2025-11-12T23:10:00Z
        """
        try:
            QMessageBox.information(
                self.parent,
                "SimplePySideApp",
                "Save clicked"
            )
        except Exception as e:
            self._handle_error("Save action", e)

    def on_exit(self) -> None:
        """
        Handle File → Exit action.

        Closes application cleanly by calling QApplication.quit().
        No message box is displayed (immediate action).

        Related: FR-GUI-002 (AC-GUI-002-05), BR-GUI-001
        Generated: 2025-11-12T23:10:00Z
        """
        try:
            QApplication.quit()
        except Exception as e:
            print(f"Error during exit: {e}")
            import sys
            sys.exit(1)

    def _handle_error(self, context: str, error: Exception) -> None:
        """
        Handle action errors.

        Logs error to console and displays error dialog to user.

        Args:
            context: Description of the action that failed
            error: Exception that was raised

        Related: FR-GUI-002 (BR-GUI-004)
        """
        print(f"ERROR [{context}]: {error}")
        try:
            QMessageBox.critical(
                self.parent,
                "Error",
                f"An error occurred: {context}"
            )
        except Exception:
            # If error dialog fails, just log
            pass
