"""
Help menu action handlers.

Generated by: implementation-agent
Source: docs/design/structure/CLASS-GUI-002-menu-system.md
Generated: 2025-11-12T23:10:00Z
Requirements: FR-GUI-002
"""

from typing import Optional
from PySide6.QtWidgets import QWidget, QMessageBox


class HelpActionHandler:
    """
    Handler for Help menu actions.

    Handles:
        - Help → About: Show About dialog

    Related: FR-GUI-002 (AC-GUI-002-09)
    Generated: 2025-11-12T23:10:00Z
    """

    def __init__(self, parent: QWidget):
        """
        Initialize handler with parent window reference.

        Args:
            parent: Parent widget (MainWindow)

        Related: FR-GUI-002
        """
        self.parent = parent

    def on_about(self) -> None:
        """
        Handle Help → About action.

        Displays an About dialog with application information.

        Dialog details:
            - Title: "About SimplePySideApp"
            - Message: "SimplePySideApp v1.0\\nA simple PySide6 desktop application"

        Related: FR-GUI-002 (AC-GUI-002-09)
        Generated: 2025-11-12T23:10:00Z
        """
        try:
            QMessageBox.information(
                self.parent,
                "About SimplePySideApp",
                "SimplePySideApp v1.0\nA simple PySide6 desktop application"
            )
        except Exception as e:
            self._handle_error("About action", e)

    def _handle_error(self, context: str, error: Exception) -> None:
        """
        Handle action errors.

        Logs error to console and displays error dialog to user.

        Args:
            context: Description of the action that failed
            error: Exception that was raised

        Related: FR-GUI-002 (BR-GUI-004)
        """
        print(f"ERROR [{context}]: {error}")
        try:
            QMessageBox.critical(
                self.parent,
                "Error",
                f"An error occurred: {context}"
            )
        except Exception:
            # If error dialog fails, just log
            pass
