"""
SimplePySideApp - A simple PySide6 desktop application.

Generated by: implementation-agent
Source: docs/design/structure/STRUCT-APP-001-project-layout.md
Generated: 2025-11-12T23:10:00Z
Requirements: FR-GUI-001, FR-GUI-002, FR-GUI-003
"""

__version__ = "1.0.0"
__author__ = "Implementation Agent"
__description__ = "A simple PySide6 desktop application"
