"""
SimplePySideApp - Application entry point.

Generated by: implementation-agent
Source: docs/design/structure/STRUCT-APP-001-project-layout.md
Generated: 2025-11-12T23:10:00Z
Requirements: FR-GUI-001
"""

import sys


def check_dependencies() -> None:
    """
    Check if PySide6 is available.

    Exits with code 1 if PySide6 is not installed, displaying
    installation instructions.

    Related: FR-GUI-001 (AC-GUI-001-11)
    Generated: 2025-11-12T23:10:00Z
    """
    try:
        from PySide6 import QtWidgets
    except ModuleNotFoundError:
        print("PySide6 not found. Install with: pip install PySide6")
        sys.exit(1)


def main() -> None:
    """
    Main application entry point.

    Initializes QApplication, creates MainWindow, and enters event loop.

    Process:
        1. Check PySide6 dependencies
        2. Create QApplication instance
        3. Create and show MainWindow
        4. Enter Qt event loop
        5. Exit with return code from event loop

    Related: FR-GUI-001 (AC-GUI-001-01)
    Generated: 2025-11-12T23:10:00Z
    """
    check_dependencies()

    from PySide6.QtWidgets import QApplication
    from app.presentation.main_window import MainWindow

    try:
        app = QApplication(sys.argv)
        window = MainWindow()
        window.show()
        sys.exit(app.exec())
    except Exception as e:
        print(f"Cannot initialize display: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
