"""add_auto_print_label_to_processes

Revision ID: d014b2d1886b
Revises: 0003_add_wip_unique_index
Create Date: 2025-11-24 01:25:29.377894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = 'd014b2d1886b'
down_revision = '0003_add_wip_unique_index'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_filters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('is_shared', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('print_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label_type', sa.String(length=50), nullable=False, comment='Label template type (WIP_LABEL, SERIAL_LABEL, LOT_LABEL)'),
    sa.Column('label_id', sa.String(length=255), nullable=False, comment='ID of the printed label'),
    sa.Column('process_id', sa.Integer(), nullable=True, comment='Associated process ID'),
    sa.Column('process_data_id', sa.Integer(), nullable=True, comment='Associated process data ID'),
    sa.Column('printer_ip', sa.String(length=50), nullable=True, comment='Printer IP address'),
    sa.Column('printer_port', sa.Integer(), nullable=True, comment='Printer port number'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Print status (SUCCESS/FAILED)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if print failed'),
    sa.Column('operator_id', sa.Integer(), nullable=True, comment='User who triggered the print'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Print timestamp'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['process_data_id'], ['process_data.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('print_logs', schema=None) as batch_op:
        batch_op.create_index('idx_print_logs_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_print_logs_label_type', ['label_type'], unique=False)
        batch_op.create_index('idx_print_logs_status', ['status'], unique=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)

    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)

    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)

    with op.batch_alter_table('process_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('defects', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('duration_seconds', sa.INTEGER(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('result',
               existing_type=sa.VARCHAR(length=10),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('started_at',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('completed_at',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               type_=sa.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index(batch_op.f('idx_process_data_completed'))
        batch_op.drop_index(batch_op.f('idx_process_data_data_level_lot'))
        batch_op.drop_index(batch_op.f('idx_process_data_level'))
        batch_op.drop_index(batch_op.f('idx_process_data_result'))
        batch_op.drop_index(batch_op.f('idx_process_data_started'))
        batch_op.drop_index(batch_op.f('uq_process_data_lot_process_wip'), sqlite_where=sa.text('wip_id IS NOT NULL'))
        batch_op.create_index('idx_process_data_completed_at', ['completed_at'], unique=False)
        batch_op.create_index('idx_process_data_data_level', ['data_level', 'lot_id'], unique=False)
        batch_op.create_index('idx_process_data_defects', ['defects'], unique=False)
        batch_op.create_index('idx_process_data_equipment', ['equipment_id'], unique=False)
        batch_op.create_index('idx_process_data_equipment_utilization', ['equipment_id', 'process_id', 'started_at'], unique=False)
        batch_op.create_index('idx_process_data_failed', ['process_id', 'started_at'], unique=False)
        batch_op.create_index('idx_process_data_measurements', ['measurements'], unique=False)
        batch_op.create_index('idx_process_data_operator_performance', ['operator_id', 'process_id', 'result', 'started_at'], unique=False)
        batch_op.create_index('idx_process_data_process_result', ['process_id', 'result', 'started_at'], unique=False)
        batch_op.create_index('idx_process_data_serial_process', ['serial_id', 'process_id', 'result'], unique=False)
        batch_op.create_index('idx_process_data_started_at', ['started_at'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'serials', ['serial_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'users', ['operator_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'equipment', ['equipment_id'], ['id'], onupdate='CASCADE', ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'processes', ['process_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.create_foreign_key(None, 'wip_items', ['wip_id'], ['id'], onupdate='CASCADE', ondelete='RESTRICT')
        batch_op.drop_column('parameters')
        batch_op.drop_column('defect_code')
        batch_op.drop_column('defect_reason')
        batch_op.drop_column('rework_count')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('process_time_seconds')

    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auto_print_label', sa.Boolean(), server_default=sa.text('0'), nullable=False, comment='완공 시 자동 라벨 출력 여부'))
        batch_op.add_column(sa.Column('label_template_type', sa.String(length=50), nullable=True, comment='출력할 라벨 템플릿 종류 (WIP_LABEL, SERIAL_LABEL, LOT_LABEL)'))

    with op.batch_alter_table('serials', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=False)

    with op.batch_alter_table('wip_items', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_column('notes')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wip_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.TEXT(), nullable=True))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('serials', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('processes', schema=None) as batch_op:
        batch_op.drop_column('label_template_type')
        batch_op.drop_column('auto_print_label')

    with op.batch_alter_table('process_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('process_time_seconds', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
        batch_op.add_column(sa.Column('rework_count', sa.INTEGER(), server_default=sa.text("'0'"), nullable=False))
        batch_op.add_column(sa.Column('defect_reason', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('defect_code', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('parameters', sqlite.JSON(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'equipment', ['equipment_id'], ['id'])
        batch_op.create_foreign_key(None, 'wip_items', ['wip_id'], ['id'])
        batch_op.create_foreign_key(None, 'processes', ['process_id'], ['id'])
        batch_op.create_foreign_key(None, 'users', ['operator_id'], ['id'])
        batch_op.create_foreign_key(None, 'serials', ['serial_id'], ['id'])
        batch_op.drop_index('idx_process_data_started_at')
        batch_op.drop_index('idx_process_data_serial_process')
        batch_op.drop_index('idx_process_data_process_result')
        batch_op.drop_index('idx_process_data_operator_performance')
        batch_op.drop_index('idx_process_data_measurements')
        batch_op.drop_index('idx_process_data_failed')
        batch_op.drop_index('idx_process_data_equipment_utilization')
        batch_op.drop_index('idx_process_data_equipment')
        batch_op.drop_index('idx_process_data_defects')
        batch_op.drop_index('idx_process_data_data_level')
        batch_op.drop_index('idx_process_data_completed_at')
        batch_op.create_index(batch_op.f('uq_process_data_lot_process_wip'), ['lot_id', 'process_id', 'wip_id'], unique=1, sqlite_where=sa.text('wip_id IS NOT NULL'))
        batch_op.create_index(batch_op.f('idx_process_data_started'), ['started_at'], unique=False)
        batch_op.create_index(batch_op.f('idx_process_data_result'), ['result'], unique=False)
        batch_op.create_index(batch_op.f('idx_process_data_level'), ['data_level'], unique=False)
        batch_op.create_index(batch_op.f('idx_process_data_data_level_lot'), ['data_level', 'lot_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_process_data_completed'), ['completed_at'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('completed_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=True)
        batch_op.alter_column('started_at',
               existing_type=sa.TIMESTAMP(timezone=True),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('result',
               existing_type=sa.VARCHAR(length=10),
               server_default=sa.text("'pending'"),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('duration_seconds')
        batch_op.drop_column('defects')

    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               server_default=None,
               existing_nullable=False)

    with op.batch_alter_table('print_logs', schema=None) as batch_op:
        batch_op.drop_index('idx_print_logs_status')
        batch_op.drop_index('idx_print_logs_label_type')
        batch_op.drop_index('idx_print_logs_created_at')

    op.drop_table('print_logs')
    op.drop_table('saved_filters')
    # ### end Alembic commands ###