"""
Unit tests for action handler classes.

Generated by: testing-agent
Source: app/handlers/file_actions.py, edit_actions.py, help_actions.py
Requirements: FR-GUI-002
Generated: 2025-11-12T23:00:00Z
"""

import pytest
from unittest.mock import Mock
from PySide6.QtWidgets import QWidget, QApplication


@pytest.mark.unit
class TestFileActionHandler:
    """Test suite for FileActionHandler class."""

    def test_file_action_handler_initialization(self, mock_parent_widget):
        """
        Test FileActionHandler initializes with parent reference.

        Given: Parent widget is provided
        When: FileActionHandler is created
        Then: Handler stores parent reference

        Related: FR-GUI-002
        """
        from app.handlers.file_actions import FileActionHandler

        handler = FileActionHandler(mock_parent_widget)

        assert handler.parent == mock_parent_widget

    def test_on_new_shows_message_box(self, mock_parent_widget, mock_message_box):
        """
        Test on_new action shows "New clicked" message.

        Given: FileActionHandler is initialized
        When: on_new() method is called
        Then: QMessageBox.information shows "New clicked"

        Related: FR-GUI-002 (AC-GUI-002-01, AC-GUI-002-02)
        """
        from app.handlers.file_actions import FileActionHandler

        handler = FileActionHandler(mock_parent_widget)
        handler.on_new()

        assert len(mock_message_box['information']) == 1
        assert mock_message_box['information'][0]['title'] == "SimplePySideApp"
        assert mock_message_box['information'][0]['text'] == "New clicked"

    def test_on_open_shows_message_box(self, mock_parent_widget, mock_message_box):
        """
        Test on_open action shows "Open clicked" message.

        Given: FileActionHandler is initialized
        When: on_open() method is called
        Then: QMessageBox.information shows "Open clicked"

        Related: FR-GUI-002 (AC-GUI-002-03)
        """
        from app.handlers.file_actions import FileActionHandler

        handler = FileActionHandler(mock_parent_widget)
        handler.on_open()

        assert len(mock_message_box['information']) == 1
        assert mock_message_box['information'][0]['title'] == "SimplePySideApp"
        assert mock_message_box['information'][0]['text'] == "Open clicked"

    def test_on_save_shows_message_box(self, mock_parent_widget, mock_message_box):
        """
        Test on_save action shows "Save clicked" message.

        Given: FileActionHandler is initialized
        When: on_save() method is called
        Then: QMessageBox.information shows "Save clicked"

        Related: FR-GUI-002 (AC-GUI-002-04)
        """
        from app.handlers.file_actions import FileActionHandler

        handler = FileActionHandler(mock_parent_widget)
        handler.on_save()

        assert len(mock_message_box['information']) == 1
        assert mock_message_box['information'][0]['title'] == "SimplePySideApp"
        assert mock_message_box['information'][0]['text'] == "Save clicked"

    def test_on_exit_calls_qapplication_quit(self, mock_parent_widget, mock_qapplication_quit):
        """
        Test on_exit action calls QApplication.quit().

        Given: FileActionHandler is initialized
        When: on_exit() method is called
        Then: QApplication.quit() is invoked (no message box)

        Related: FR-GUI-002 (AC-GUI-002-05), BR-GUI-001
        """
        from app.handlers.file_actions import FileActionHandler

        handler = FileActionHandler(mock_parent_widget)
        handler.on_exit()

        assert len(mock_qapplication_quit) == 1

    def test_on_exit_does_not_show_message_box(self, mock_parent_widget, mock_message_box, mock_qapplication_quit):
        """
        Test on_exit does NOT show message box (immediate action).

        Given: FileActionHandler is initialized
        When: on_exit() is called
        Then: No message box is displayed

        Related: FR-GUI-002 (AC-GUI-002-05)
        """
        from app.handlers.file_actions import FileActionHandler

        handler = FileActionHandler(mock_parent_widget)
        handler.on_exit()

        assert len(mock_message_box['information']) == 0
        assert len(mock_message_box['critical']) == 0

    def test_multiple_new_action_calls(self, mock_parent_widget, mock_message_box):
        """
        Test multiple calls to on_new each show message box.

        Given: FileActionHandler is initialized
        When: on_new() is called 3 times
        Then: 3 message boxes are shown

        Related: FR-GUI-002 (AC-GUI-002-12)
        """
        from app.handlers.file_actions import FileActionHandler

        handler = FileActionHandler(mock_parent_widget)

        handler.on_new()
        handler.on_new()
        handler.on_new()

        assert len(mock_message_box['information']) == 3
        for msg in mock_message_box['information']:
            assert msg['text'] == "New clicked"

    def test_file_handler_has_error_handling_method(self, mock_parent_widget):
        """
        Test FileActionHandler has _handle_error method.

        Given: FileActionHandler class is defined
        When: Class methods are inspected
        Then: _handle_error method exists

        Related: FR-GUI-002 (BR-GUI-004)
        """
        from app.handlers.file_actions import FileActionHandler

        handler = FileActionHandler(mock_parent_widget)
        assert hasattr(handler, '_handle_error')

    def test_action_handler_error_handling(self, mock_parent_widget, mock_message_box, monkeypatch):
        """
        Test action handler handles exceptions gracefully.

        Given: FileActionHandler is initialized
        When: on_new raises exception (mock QMessageBox to raise)
        Then: Error is caught and handled without crashing

        Related: FR-GUI-002 (BR-GUI-004)
        """
        from app.handlers.file_actions import FileActionHandler
        from PySide6.QtWidgets import QMessageBox

        # Mock QMessageBox.information to raise exception
        def mock_error(*args):
            raise RuntimeError("Simulated error")

        monkeypatch.setattr(QMessageBox, "information", mock_error)

        handler = FileActionHandler(mock_parent_widget)

        # Should not crash
        try:
            handler.on_new()
            # If error handler works, it should show critical message
        except RuntimeError:
            # If no error handler, exception propagates
            pytest.fail("Action handler should catch and handle exceptions")


@pytest.mark.unit
class TestEditActionHandler:
    """Test suite for EditActionHandler class."""

    def test_edit_action_handler_initialization(self, mock_parent_widget):
        """
        Test EditActionHandler initializes with parent reference.

        Given: Parent widget is provided
        When: EditActionHandler is created
        Then: Handler stores parent reference

        Related: FR-GUI-002
        """
        from app.handlers.edit_actions import EditActionHandler

        handler = EditActionHandler(mock_parent_widget)

        assert handler.parent == mock_parent_widget

    def test_on_undo_shows_message_box(self, mock_parent_widget, mock_message_box):
        """
        Test on_undo action shows "Undo clicked" message.

        Given: EditActionHandler is initialized
        When: on_undo() method is called
        Then: QMessageBox.information shows "Undo clicked"

        Related: FR-GUI-002 (AC-GUI-002-07)
        """
        from app.handlers.edit_actions import EditActionHandler

        handler = EditActionHandler(mock_parent_widget)
        handler.on_undo()

        assert len(mock_message_box['information']) == 1
        assert mock_message_box['information'][0]['title'] == "SimplePySideApp"
        assert mock_message_box['information'][0]['text'] == "Undo clicked"

    def test_on_redo_shows_message_box(self, mock_parent_widget, mock_message_box):
        """
        Test on_redo action shows "Redo clicked" message.

        Given: EditActionHandler is initialized
        When: on_redo() method is called
        Then: QMessageBox.information shows "Redo clicked"

        Related: FR-GUI-002 (AC-GUI-002-08)
        """
        from app.handlers.edit_actions import EditActionHandler

        handler = EditActionHandler(mock_parent_widget)
        handler.on_redo()

        assert len(mock_message_box['information']) == 1
        assert mock_message_box['information'][0]['title'] == "SimplePySideApp"
        assert mock_message_box['information'][0]['text'] == "Redo clicked"

    def test_edit_handler_has_error_handling_method(self, mock_parent_widget):
        """
        Test EditActionHandler has _handle_error method.

        Given: EditActionHandler class is defined
        When: Class methods are inspected
        Then: _handle_error method exists

        Related: FR-GUI-002 (BR-GUI-004)
        """
        from app.handlers.edit_actions import EditActionHandler

        handler = EditActionHandler(mock_parent_widget)
        assert hasattr(handler, '_handle_error')


@pytest.mark.unit
class TestHelpActionHandler:
    """Test suite for HelpActionHandler class."""

    def test_help_action_handler_initialization(self, mock_parent_widget):
        """
        Test HelpActionHandler initializes with parent reference.

        Given: Parent widget is provided
        When: HelpActionHandler is created
        Then: Handler stores parent reference

        Related: FR-GUI-002
        """
        from app.handlers.help_actions import HelpActionHandler

        handler = HelpActionHandler(mock_parent_widget)

        assert handler.parent == mock_parent_widget

    def test_on_about_shows_correct_dialog(self, mock_parent_widget, mock_message_box):
        """
        Test on_about shows About dialog with correct information.

        Given: HelpActionHandler is initialized
        When: on_about() method is called
        Then: QMessageBox shows "About SimplePySideApp" title and version info

        Related: FR-GUI-002 (AC-GUI-002-09)
        """
        from app.handlers.help_actions import HelpActionHandler

        handler = HelpActionHandler(mock_parent_widget)
        handler.on_about()

        assert len(mock_message_box['information']) == 1
        assert mock_message_box['information'][0]['title'] == "About SimplePySideApp"

        # Message should contain version and description
        message = mock_message_box['information'][0]['text']
        assert "SimplePySideApp" in message
        assert "v1.0" in message or "1.0" in message
        assert "PySide6" in message

    def test_help_handler_has_error_handling_method(self, mock_parent_widget):
        """
        Test HelpActionHandler has _handle_error method.

        Given: HelpActionHandler class is defined
        When: Class methods are inspected
        Then: _handle_error method exists

        Related: FR-GUI-002 (BR-GUI-004)
        """
        from app.handlers.help_actions import HelpActionHandler

        handler = HelpActionHandler(mock_parent_widget)
        assert hasattr(handler, '_handle_error')


@pytest.mark.unit
class TestActionHandlerSequence:
    """Test suite for action handler call sequences."""

    def test_sequential_different_actions_independent(self, mock_parent_widget, mock_message_box):
        """
        Test sequential different actions are independent.

        Given: Action handlers are initialized
        When: Multiple different actions are triggered in sequence
        Then: Each action shows correct message (no state pollution)

        Related: FR-GUI-002 (AC-GUI-002-17)
        """
        from app.handlers.file_actions import FileActionHandler
        from app.handlers.edit_actions import EditActionHandler

        file_handler = FileActionHandler(mock_parent_widget)
        edit_handler = EditActionHandler(mock_parent_widget)

        # Sequence: New → Open → Save → Undo
        file_handler.on_new()
        file_handler.on_open()
        file_handler.on_save()
        edit_handler.on_undo()

        assert len(mock_message_box['information']) == 4
        assert mock_message_box['information'][0]['text'] == "New clicked"
        assert mock_message_box['information'][1]['text'] == "Open clicked"
        assert mock_message_box['information'][2]['text'] == "Save clicked"
        assert mock_message_box['information'][3]['text'] == "Undo clicked"

    def test_handlers_do_not_share_state(self, mock_parent_widget):
        """
        Test different handler instances do not share state.

        Given: Two FileActionHandler instances are created
        When: Handlers are compared
        Then: They are independent instances

        Related: FR-GUI-002
        """
        from app.handlers.file_actions import FileActionHandler

        handler1 = FileActionHandler(mock_parent_widget)
        handler2 = FileActionHandler(mock_parent_widget)

        assert handler1 is not handler2
        assert id(handler1) != id(handler2)


@pytest.mark.unit
class TestActionHandlerEdgeCases:
    """Test suite for action handler edge cases."""

    def test_handler_with_none_parent(self):
        """
        Test handler creation with None parent.

        Given: FileActionHandler is created with None parent
        When: Handler is initialized
        Then: Either succeeds or raises TypeError

        Related: FR-GUI-002
        """
        from app.handlers.file_actions import FileActionHandler

        try:
            handler = FileActionHandler(None)
            assert handler.parent is None
        except (TypeError, AttributeError):
            # Acceptable if handler requires valid parent
            pass

    def test_rapid_action_calls_no_crash(self, mock_parent_widget, mock_message_box):
        """
        Test rapid action calls don't crash application.

        Given: FileActionHandler is initialized
        When: on_new is called 100 times rapidly
        Then: All calls succeed without crash

        Related: FR-GUI-002 (AC-GUI-002-12)
        """
        from app.handlers.file_actions import FileActionHandler

        handler = FileActionHandler(mock_parent_widget)

        # Rapid calls
        for _ in range(100):
            handler.on_new()

        assert len(mock_message_box['information']) == 100

    def test_double_exit_call_handled_gracefully(self, mock_parent_widget, mock_qapplication_quit):
        """
        Test double exit call is handled gracefully.

        Given: FileActionHandler is initialized
        When: on_exit() is called twice rapidly
        Then: No errors occur (second call is idempotent)

        Related: FR-GUI-002 (AC-GUI-002-13)
        """
        from app.handlers.file_actions import FileActionHandler

        handler = FileActionHandler(mock_parent_widget)

        # First exit call
        handler.on_exit()
        assert len(mock_qapplication_quit) == 1

        # Second exit call (should be safe)
        handler.on_exit()
        assert len(mock_qapplication_quit) == 2
