"""
Unit tests for menu system creation functions.

Generated by: testing-agent
Source: app/presentation/menu_bar.py
Requirements: FR-GUI-002
Generated: 2025-11-12T23:00:00Z
"""

import pytest
from PySide6.QtWidgets import QWidget, QMenuBar, QMenu
from PySide6.QtGui import QKeySequence, QAction


@pytest.mark.unit
class TestMenuBarCreation:
    """Test suite for menu bar creation."""

    def test_create_menu_bar_returns_qmenubar(self):
        """
        Test create_menu_bar returns QMenuBar instance.

        Given: create_menu_bar function is called with parent widget
        When: Function executes
        Then: Returns QMenuBar instance

        Related: FR-GUI-002
        """
        from app.presentation.menu_bar import create_menu_bar

        parent = QWidget()
        menu_bar = create_menu_bar(parent)

        assert isinstance(menu_bar, QMenuBar)

    def test_menu_bar_has_three_menus(self):
        """
        Test menu bar contains exactly three menus (File, Edit, Help).

        Given: Menu bar is created
        When: Menu actions are queried
        Then: Three menus exist with correct titles

        Related: FR-GUI-002 (AC-GUI-002-01)
        """
        from app.presentation.menu_bar import create_menu_bar

        parent = QWidget()
        menu_bar = create_menu_bar(parent)

        actions = menu_bar.actions()
        assert len(actions) == 3

        menu_titles = [action.text().replace('&', '') for action in actions]
        assert menu_titles == ["File", "Edit", "Help"]

    def test_menu_bar_menus_are_qmenu_instances(self):
        """
        Test each menu in menu bar is a QMenu instance.

        Given: Menu bar is created with menus
        When: Each menu is inspected
        Then: Each is a QMenu instance

        Related: FR-GUI-002
        """
        from app.presentation.menu_bar import create_menu_bar

        parent = QWidget()
        menu_bar = create_menu_bar(parent)

        for action in menu_bar.actions():
            menu = action.menu()
            assert isinstance(menu, QMenu)


@pytest.mark.unit
class TestFileMenuCreation:
    """Test suite for File menu creation."""

    def test_create_file_menu_returns_qmenu(self):
        """
        Test create_file_menu returns QMenu instance.

        Given: create_file_menu function is called
        When: Function executes
        Then: Returns QMenu instance

        Related: FR-GUI-002
        """
        from app.presentation.menu_bar import create_file_menu

        parent = QWidget()
        file_menu = create_file_menu(parent)

        assert isinstance(file_menu, QMenu)

    def test_file_menu_title_is_file(self):
        """
        Test File menu has correct title.

        Given: File menu is created
        When: Menu title is queried
        Then: Title is "&File" (with mnemonic)

        Related: FR-GUI-002
        """
        from app.presentation.menu_bar import create_file_menu

        parent = QWidget()
        file_menu = create_file_menu(parent)

        assert file_menu.title() == "&File"

    def test_file_menu_has_five_items_including_separator(self):
        """
        Test File menu has 5 items: New, Open, Save, Separator, Exit.

        Given: File menu is created
        When: Menu actions are counted
        Then: Five actions exist (including separator)

        Related: FR-GUI-002 (AC-GUI-002-06)
        """
        from app.presentation.menu_bar import create_file_menu

        parent = QWidget()
        file_menu = create_file_menu(parent)

        actions = file_menu.actions()
        assert len(actions) == 5

    def test_file_menu_has_separator_before_exit(self):
        """
        Test File menu has separator before Exit action.

        Given: File menu is created
        When: Actions are inspected
        Then: Fourth action is a separator

        Related: FR-GUI-002 (AC-GUI-002-06, BR-GUI-007)
        """
        from app.presentation.menu_bar import create_file_menu

        parent = QWidget()
        file_menu = create_file_menu(parent)

        actions = file_menu.actions()
        assert actions[3].isSeparator()

    def test_file_menu_action_texts(self):
        """
        Test File menu action texts are correct.

        Given: File menu is created
        When: Action texts are queried (excluding separator)
        Then: Actions are New, Open, Save, Exit

        Related: FR-GUI-002
        """
        from app.presentation.menu_bar import create_file_menu

        parent = QWidget()
        file_menu = create_file_menu(parent)

        actions = [a for a in file_menu.actions() if not a.isSeparator()]
        action_texts = [a.text().replace('&', '') for a in actions]

        expected = ["New", "Open", "Save", "Exit"]
        assert action_texts == expected

    def test_file_menu_new_action_has_shortcut(self):
        """
        Test New action has Ctrl+N shortcut.

        Given: File menu is created
        When: New action shortcut is queried
        Then: Shortcut is Ctrl+N

        Related: FR-GUI-002 (AC-GUI-002-02, AC-GUI-002-10)
        """
        from app.presentation.menu_bar import create_file_menu

        parent = QWidget()
        file_menu = create_file_menu(parent)

        new_action = file_menu.actions()[0]
        shortcut = new_action.shortcut()

        assert shortcut == QKeySequence.New
        # Verify it matches Ctrl+N on Windows/Linux
        assert shortcut.toString() in ["Ctrl+N", "Meta+N"]  # Meta for macOS

    def test_file_menu_open_action_has_shortcut(self):
        """
        Test Open action has Ctrl+O shortcut.

        Given: File menu is created
        When: Open action shortcut is queried
        Then: Shortcut is Ctrl+O

        Related: FR-GUI-002 (AC-GUI-002-03, AC-GUI-002-10)
        """
        from app.presentation.menu_bar import create_file_menu

        parent = QWidget()
        file_menu = create_file_menu(parent)

        open_action = file_menu.actions()[1]
        shortcut = open_action.shortcut()

        assert shortcut == QKeySequence.Open
        assert shortcut.toString() in ["Ctrl+O", "Meta+O"]

    def test_file_menu_save_action_has_shortcut(self):
        """
        Test Save action has Ctrl+S shortcut.

        Given: File menu is created
        When: Save action shortcut is queried
        Then: Shortcut is Ctrl+S

        Related: FR-GUI-002 (AC-GUI-002-04, AC-GUI-002-10)
        """
        from app.presentation.menu_bar import create_file_menu

        parent = QWidget()
        file_menu = create_file_menu(parent)

        save_action = file_menu.actions()[2]
        shortcut = save_action.shortcut()

        assert shortcut == QKeySequence.Save
        assert shortcut.toString() in ["Ctrl+S", "Meta+S"]

    def test_file_menu_exit_action_has_shortcut(self):
        """
        Test Exit action has Ctrl+Q shortcut.

        Given: File menu is created
        When: Exit action shortcut is queried
        Then: Shortcut is Ctrl+Q

        Related: FR-GUI-002 (AC-GUI-002-05, AC-GUI-002-10)
        """
        from app.presentation.menu_bar import create_file_menu

        parent = QWidget()
        file_menu = create_file_menu(parent)

        exit_action = file_menu.actions()[4]  # After separator
        shortcut = exit_action.shortcut()

        assert shortcut == QKeySequence.Quit
        assert shortcut.toString() in ["Ctrl+Q", "Meta+Q"]


@pytest.mark.unit
class TestEditMenuCreation:
    """Test suite for Edit menu creation."""

    def test_create_edit_menu_returns_qmenu(self):
        """
        Test create_edit_menu returns QMenu instance.

        Given: create_edit_menu function is called
        When: Function executes
        Then: Returns QMenu instance

        Related: FR-GUI-002
        """
        from app.presentation.menu_bar import create_edit_menu

        parent = QWidget()
        edit_menu = create_edit_menu(parent)

        assert isinstance(edit_menu, QMenu)

    def test_edit_menu_title_is_edit(self):
        """
        Test Edit menu has correct title.

        Given: Edit menu is created
        When: Menu title is queried
        Then: Title is "&Edit"

        Related: FR-GUI-002
        """
        from app.presentation.menu_bar import create_edit_menu

        parent = QWidget()
        edit_menu = create_edit_menu(parent)

        assert edit_menu.title() == "&Edit"

    def test_edit_menu_has_two_actions(self):
        """
        Test Edit menu has exactly 2 actions: Undo, Redo.

        Given: Edit menu is created
        When: Actions are counted
        Then: Two actions exist

        Related: FR-GUI-002
        """
        from app.presentation.menu_bar import create_edit_menu

        parent = QWidget()
        edit_menu = create_edit_menu(parent)

        actions = edit_menu.actions()
        assert len(actions) == 2

    def test_edit_menu_action_texts(self):
        """
        Test Edit menu action texts are correct.

        Given: Edit menu is created
        When: Action texts are queried
        Then: Actions are Undo, Redo

        Related: FR-GUI-002
        """
        from app.presentation.menu_bar import create_edit_menu

        parent = QWidget()
        edit_menu = create_edit_menu(parent)

        action_texts = [a.text().replace('&', '') for a in edit_menu.actions()]
        assert action_texts == ["Undo", "Redo"]

    def test_edit_menu_undo_action_has_shortcut(self):
        """
        Test Undo action has Ctrl+Z shortcut.

        Given: Edit menu is created
        When: Undo action shortcut is queried
        Then: Shortcut is Ctrl+Z

        Related: FR-GUI-002 (AC-GUI-002-07, AC-GUI-002-10)
        """
        from app.presentation.menu_bar import create_edit_menu

        parent = QWidget()
        edit_menu = create_edit_menu(parent)

        undo_action = edit_menu.actions()[0]
        shortcut = undo_action.shortcut()

        assert shortcut == QKeySequence.Undo
        assert shortcut.toString() in ["Ctrl+Z", "Meta+Z"]

    def test_edit_menu_redo_action_has_shortcut(self):
        """
        Test Redo action has Ctrl+Y or Ctrl+Shift+Z shortcut.

        Given: Edit menu is created
        When: Redo action shortcut is queried
        Then: Shortcut is Ctrl+Y (Windows) or Ctrl+Shift+Z (macOS)

        Related: FR-GUI-002 (AC-GUI-002-08, AC-GUI-002-10)
        """
        from app.presentation.menu_bar import create_edit_menu

        parent = QWidget()
        edit_menu = create_edit_menu(parent)

        redo_action = edit_menu.actions()[1]
        shortcut = redo_action.shortcut()

        assert shortcut == QKeySequence.Redo
        # Platform-specific: Ctrl+Y on Windows, Cmd+Shift+Z on macOS
        assert shortcut.toString() in ["Ctrl+Y", "Ctrl+Shift+Z", "Meta+Shift+Z"]


@pytest.mark.unit
class TestHelpMenuCreation:
    """Test suite for Help menu creation."""

    def test_create_help_menu_returns_qmenu(self):
        """
        Test create_help_menu returns QMenu instance.

        Given: create_help_menu function is called
        When: Function executes
        Then: Returns QMenu instance

        Related: FR-GUI-002
        """
        from app.presentation.menu_bar import create_help_menu

        parent = QWidget()
        help_menu = create_help_menu(parent)

        assert isinstance(help_menu, QMenu)

    def test_help_menu_title_is_help(self):
        """
        Test Help menu has correct title.

        Given: Help menu is created
        When: Menu title is queried
        Then: Title is "&Help"

        Related: FR-GUI-002
        """
        from app.presentation.menu_bar import create_help_menu

        parent = QWidget()
        help_menu = create_help_menu(parent)

        assert help_menu.title() == "&Help"

    def test_help_menu_has_one_action(self):
        """
        Test Help menu has exactly 1 action: About.

        Given: Help menu is created
        When: Actions are counted
        Then: One action exists

        Related: FR-GUI-002
        """
        from app.presentation.menu_bar import create_help_menu

        parent = QWidget()
        help_menu = create_help_menu(parent)

        actions = help_menu.actions()
        assert len(actions) == 1

    def test_help_menu_about_action_text(self):
        """
        Test About action has correct text.

        Given: Help menu is created
        When: About action text is queried
        Then: Text is "&About"

        Related: FR-GUI-002 (AC-GUI-002-09)
        """
        from app.presentation.menu_bar import create_help_menu

        parent = QWidget()
        help_menu = create_help_menu(parent)

        about_action = help_menu.actions()[0]
        assert about_action.text() == "&About"

    def test_help_menu_about_action_no_shortcut(self):
        """
        Test About action has no keyboard shortcut.

        Given: Help menu is created
        When: About action shortcut is queried
        Then: No shortcut is assigned

        Related: FR-GUI-002 (AC-GUI-002-09)
        """
        from app.presentation.menu_bar import create_help_menu

        parent = QWidget()
        help_menu = create_help_menu(parent)

        about_action = help_menu.actions()[0]
        shortcut = about_action.shortcut()

        assert shortcut.isEmpty()


@pytest.mark.unit
class TestMenuCreationEdgeCases:
    """Test suite for menu creation edge cases."""

    def test_create_menu_bar_with_none_parent(self):
        """
        Test create_menu_bar handles None parent gracefully.

        Given: create_menu_bar is called with None as parent
        When: Function executes
        Then: Either returns QMenuBar or raises TypeError

        Related: FR-GUI-002, BR-GUI-004
        """
        from app.presentation.menu_bar import create_menu_bar

        # This should either work or raise TypeError
        try:
            menu_bar = create_menu_bar(None)
            assert isinstance(menu_bar, QMenuBar) or menu_bar is None
        except TypeError:
            # Expected behavior - Qt requires parent
            pass

    def test_multiple_menu_bar_creation_independent(self):
        """
        Test creating multiple menu bars produces independent instances.

        Given: Two menu bars are created with different parents
        When: Menu bars are compared
        Then: They are different instances

        Related: FR-GUI-002
        """
        from app.presentation.menu_bar import create_menu_bar

        parent1 = QWidget()
        parent2 = QWidget()

        menu_bar1 = create_menu_bar(parent1)
        menu_bar2 = create_menu_bar(parent2)

        assert menu_bar1 is not menu_bar2
        assert id(menu_bar1) != id(menu_bar2)

    def test_menu_actions_are_not_connected_by_default(self):
        """
        Test menu actions are not connected to slots by default.

        Given: File menu is created
        When: New action signal connections are inspected
        Then: No default connections exist (handler must connect later)

        Related: FR-GUI-002
        """
        from app.presentation.menu_bar import create_file_menu

        parent = QWidget()
        file_menu = create_file_menu(parent)

        new_action = file_menu.actions()[0]

        # Action should exist but not be connected yet
        # (MainWindow connects them later)
        assert new_action is not None
        assert isinstance(new_action, QAction)
