"""
Main application window for SimplePySideApp.

Generated by: implementation-agent
Source: docs/design/structure/CLASS-GUI-001-main-window.md
Generated: 2025-11-12T23:10:00Z
Requirements: FR-GUI-001, FR-GUI-002, FR-GUI-003
"""

from typing import Optional
from PySide6.QtWidgets import QMainWindow, QWidget, QMenuBar, QMenu
from PySide6.QtCore import QSize
from PySide6.QtGui import QCloseEvent

from app.presentation.menu_bar import create_menu_bar
from app.handlers.file_actions import FileActionHandler
from app.handlers.edit_actions import EditActionHandler
from app.handlers.help_actions import HelpActionHandler


class MainWindow(QMainWindow):
    """
    Main application window.

    Provides:
        - Window management (title, size, state)
        - Menu bar with File, Edit, Help menus
        - Central widget (empty for this phase)
        - Event handling coordination

    Window Properties:
        - Title: "SimplePySideApp"
        - Default size: 800x600 pixels
        - Minimum size: 400x300 pixels

    Related: FR-GUI-001, FR-GUI-002
    Generated: 2025-11-12T23:10:00Z
    """

    # Class constants
    WINDOW_TITLE: str = "SimplePySideApp"
    DEFAULT_WIDTH: int = 800
    DEFAULT_HEIGHT: int = 600
    MIN_WIDTH: int = 400
    MIN_HEIGHT: int = 300

    def __init__(self):
        """
        Initialize the main window.

        Creates window, sets up UI components, and connects signals to handlers.

        Related: FR-GUI-001 (AC-GUI-001-01)
        Generated: 2025-11-12T23:10:00Z
        """
        super().__init__()
        self._init_ui()

    def _init_ui(self) -> None:
        """
        Initialize UI components.

        Calls private methods to set up:
            - Window properties (title, size)
            - Central widget
            - Menu bar
            - Signal/slot connections

        Related: FR-GUI-001
        Generated: 2025-11-12T23:10:00Z
        """
        self._setup_window_properties()
        self._create_central_widget()
        self._create_menu_bar()
        self._connect_actions()

    def _setup_window_properties(self) -> None:
        """
        Set up window properties.

        Configures:
            - Window title
            - Default size (800x600)
            - Minimum size (400x300)

        Related: FR-GUI-001 (AC-GUI-001-01, BR-GUI-002)
        Generated: 2025-11-12T23:10:00Z
        """
        self.setWindowTitle(self.WINDOW_TITLE)
        self.resize(self.DEFAULT_WIDTH, self.DEFAULT_HEIGHT)
        self.setMinimumSize(self.MIN_WIDTH, self.MIN_HEIGHT)

    def _create_central_widget(self) -> None:
        """
        Create central widget.

        Creates an empty QWidget and sets it as the central widget.
        This serves as a placeholder for future content.

        Related: FR-GUI-001 (AC-GUI-001-01), FR-GUI-003 (AC-GUI-003-19)
        Generated: 2025-11-12T23:10:00Z
        """
        self._central_widget = QWidget()
        self.setCentralWidget(self._central_widget)

    def _create_menu_bar(self) -> None:
        """
        Create menu bar.

        Creates menu bar with File, Edit, Help menus using
        the create_menu_bar factory function.

        Related: FR-GUI-002 (AC-GUI-002-01 through AC-GUI-002-09)
        Generated: 2025-11-12T23:10:00Z
        """
        self._menu_bar = create_menu_bar(self)
        self.setMenuBar(self._menu_bar)

    def _connect_actions(self) -> None:
        """
        Connect menu actions to handlers.

        Creates action handler instances and connects menu action signals
        to handler methods using Qt's signal/slot mechanism.

        Connections:
            - File menu actions → FileActionHandler methods
            - Edit menu actions → EditActionHandler methods
            - Help menu actions → HelpActionHandler methods

        Related: FR-GUI-002 (All acceptance criteria)
        Generated: 2025-11-12T23:10:00Z
        """
        # Create action handlers
        self._file_handler = FileActionHandler(self)
        self._edit_handler = EditActionHandler(self)
        self._help_handler = HelpActionHandler(self)

        # Get menus from menu bar
        menus = self.menuBar().actions()

        # Connect File menu actions
        file_menu = menus[0].menu()
        file_actions = file_menu.actions()
        for action in file_actions:
            if action.isSeparator():
                continue
            text = action.text().replace('&', '')
            if text == "New":
                action.triggered.connect(self._file_handler.on_new)
            elif text == "Open":
                action.triggered.connect(self._file_handler.on_open)
            elif text == "Save":
                action.triggered.connect(self._file_handler.on_save)
            elif text == "Exit":
                action.triggered.connect(self._file_handler.on_exit)

        # Connect Edit menu actions
        edit_menu = menus[1].menu()
        edit_actions = edit_menu.actions()
        for action in edit_actions:
            text = action.text().replace('&', '')
            if text == "Undo":
                action.triggered.connect(self._edit_handler.on_undo)
            elif text == "Redo":
                action.triggered.connect(self._edit_handler.on_redo)

        # Connect Help menu actions
        help_menu = menus[2].menu()
        help_actions = help_menu.actions()
        for action in help_actions:
            text = action.text().replace('&', '')
            if text == "About":
                action.triggered.connect(self._help_handler.on_about)

    def closeEvent(self, event: QCloseEvent) -> None:
        """
        Handle window close event.

        Accepts the close event to allow window to close.
        The Exit action handler will call QApplication.quit().

        Args:
            event: Close event object

        Related: FR-GUI-001 (AC-GUI-001-07, BR-GUI-001), FR-GUI-002 (AC-GUI-002-05)
        Generated: 2025-11-12T23:10:00Z
        """
        event.accept()
