"""
Menu bar creation for SimplePySideApp.

Generated by: implementation-agent
Source: docs/design/structure/CLASS-GUI-002-menu-system.md
Generated: 2025-11-12T23:10:00Z
Requirements: FR-GUI-002
"""

from typing import Optional
from PySide6.QtWidgets import QMenuBar, QMenu, QWidget
from PySide6.QtGui import QAction, QKeySequence


def create_menu_bar(parent: QWidget) -> QMenuBar:
    """
    Create the main menu bar with File, Edit, Help menus.

    Args:
        parent: Parent widget (MainWindow)

    Returns:
        QMenuBar: Configured menu bar with all menus

    Related: FR-GUI-002 (AC-GUI-002-01)
    Generated: 2025-11-12T23:10:00Z
    """
    menu_bar = QMenuBar(parent)

    file_menu = create_file_menu(parent)
    edit_menu = create_edit_menu(parent)
    help_menu = create_help_menu(parent)

    menu_bar.addMenu(file_menu)
    menu_bar.addMenu(edit_menu)
    menu_bar.addMenu(help_menu)

    return menu_bar


def create_file_menu(parent: QWidget) -> QMenu:
    """
    Create File menu with New, Open, Save, Exit actions.

    Args:
        parent: Parent widget

    Returns:
        QMenu: File menu with actions and keyboard shortcuts

    Menu Structure:
        File
        ├── New       (Ctrl+N)
        ├── Open      (Ctrl+O)
        ├── Save      (Ctrl+S)
        ├── ─────────  (separator)
        └── Exit      (Ctrl+Q)

    Related: FR-GUI-002 (AC-GUI-002-01 through AC-GUI-002-06)
    Generated: 2025-11-12T23:10:00Z
    """
    file_menu = QMenu("&File", parent)

    # New action
    new_action = QAction("&New", parent)
    new_action.setShortcut(QKeySequence.New)  # Ctrl+N
    file_menu.addAction(new_action)

    # Open action
    open_action = QAction("&Open", parent)
    open_action.setShortcut(QKeySequence.Open)  # Ctrl+O
    file_menu.addAction(open_action)

    # Save action
    save_action = QAction("&Save", parent)
    save_action.setShortcut(QKeySequence.Save)  # Ctrl+S
    file_menu.addAction(save_action)

    # Separator before Exit
    file_menu.addSeparator()

    # Exit action
    exit_action = QAction("E&xit", parent)
    exit_action.setShortcut(QKeySequence.Quit)  # Ctrl+Q
    file_menu.addAction(exit_action)

    return file_menu


def create_edit_menu(parent: QWidget) -> QMenu:
    """
    Create Edit menu with Undo, Redo actions.

    Args:
        parent: Parent widget

    Returns:
        QMenu: Edit menu with actions and keyboard shortcuts

    Menu Structure:
        Edit
        ├── Undo      (Ctrl+Z)
        └── Redo      (Ctrl+Y)

    Related: FR-GUI-002 (AC-GUI-002-07, AC-GUI-002-08)
    Generated: 2025-11-12T23:10:00Z
    """
    edit_menu = QMenu("&Edit", parent)

    # Undo action
    undo_action = QAction("&Undo", parent)
    undo_action.setShortcut(QKeySequence.Undo)  # Ctrl+Z
    edit_menu.addAction(undo_action)

    # Redo action
    redo_action = QAction("&Redo", parent)
    redo_action.setShortcut(QKeySequence.Redo)  # Ctrl+Y or Ctrl+Shift+Z
    edit_menu.addAction(redo_action)

    return edit_menu


def create_help_menu(parent: QWidget) -> QMenu:
    """
    Create Help menu with About action.

    Args:
        parent: Parent widget

    Returns:
        QMenu: Help menu with About action

    Menu Structure:
        Help
        └── About

    Related: FR-GUI-002 (AC-GUI-002-09)
    Generated: 2025-11-12T23:10:00Z
    """
    help_menu = QMenu("&Help", parent)

    # About action
    about_action = QAction("&About", parent)
    help_menu.addAction(about_action)

    return help_menu
